import { describe, expect, it, vi } from "vitest";
import { downloadRemoteImageSafely } from "@/lib/ai/image/download";

const png = new Uint8Array([137,80,78,71,13,10,26,10,0,0]);
const publicLookup = vi.fn().mockResolvedValue([{ address: "93.184.216.34" }]);

describe("secure remote image download", () => {
  it.each(["http://images.example/a.png", "https://user:pass@images.example/a.png", "https://localhost/a.png", "https://127.0.0.1/a.png", "https://10.0.0.1/a.png", "https://169.254.169.254/latest/meta-data"])('rejects unsafe URL %s', async (url) => { await expect(downloadRemoteImageSafely(url, { fetcher: vi.fn(), lookup: publicLookup })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); });
  it("rejects a hostname resolving to a private address", async () => { await expect(downloadRemoteImageSafely("https://images.example/a.png", { fetcher: vi.fn(), lookup: vi.fn().mockResolvedValue([{ address: "192.168.1.2" }]) })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); });
  it("accepts PNG magic and returns a safe extension", async () => { const fetcher = vi.fn().mockResolvedValue(new Response(png, { headers: { "content-type": "image/png" } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher, lookup: publicLookup })).resolves.toMatchObject({ mimeType: "image/png", extension: "png" }); });
  it("allows octet-stream only when magic is valid", async () => { const ok = vi.fn().mockResolvedValue(new Response(png, { headers: { "content-type": "application/octet-stream" } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher: ok, lookup: publicLookup })).resolves.toMatchObject({ extension: "png" }); const bad = vi.fn().mockResolvedValue(new Response(new Uint8Array([1,2,3]), { headers: { "content-type": "application/octet-stream" } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher: bad, lookup: publicLookup })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); });
  it("rejects HTML and a declared oversize image", async () => { const html = vi.fn().mockResolvedValue(new Response("<html>", { headers: { "content-type": "text/html" } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher: html, lookup: publicLookup })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); const large = vi.fn().mockResolvedValue(new Response(png, { headers: { "content-type": "image/png", "content-length": String(16 * 1024 * 1024) } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher: large, lookup: publicLookup })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); });
  it("revalidates every redirect target", async () => { const fetcher = vi.fn().mockResolvedValueOnce(new Response(null, { status: 302, headers: { location: "https://10.0.0.2/a.png" } })); await expect(downloadRemoteImageSafely("https://images.example/a", { fetcher, lookup: publicLookup })).rejects.toMatchObject({ code: "UNSAFE_IMAGE" }); expect(fetcher).toHaveBeenCalledTimes(1); });
});
