"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/database/prisma";
import { requireUser } from "@/lib/auth/session";
import { validateMemoryRelations } from "@/features/memory/access";
import { memoryIdSchema, memoryInputSchema, type MemoryInput } from "@/features/memory/schemas";
import { containsHighConfidenceCredential, normalizeMemoryContent } from "@/features/memory/security";
import type { MemoryActionResult } from "@/features/memory/types";
import { getMemoryMaxTotal } from "@/features/memory/constants";

const failure = (message: string, fieldErrors?: Record<string, string[]>): MemoryActionResult => ({ success: false, message, fieldErrors });
async function duplicateExists(userId: string, content: string, scope: "GLOBAL" | "PERSONA", personaId?: string, excludeId?: string) { const rows = await prisma.memory.findMany({ where: { userId, scope, personaId: scope === "GLOBAL" ? null : personaId, ...(excludeId ? { id: { not: excludeId } } : {}) }, select: { content: true } }); const normalized = normalizeMemoryContent(content); return rows.some((row) => normalizeMemoryContent(row.content) === normalized); }
function memoryData(data: ReturnType<typeof memoryInputSchema.parse>) { return { content: data.content, category: data.category, scope: data.scope, personaId: data.scope === "PERSONA" ? data.personaId : null, importance: data.importance, enabled: data.enabled, origin: data.origin, sourceConversationId: data.sourceConversationId ?? null, sourceMessageId: data.sourceMessageId ?? null }; }
export async function createMemoryAction(input: MemoryInput): Promise<MemoryActionResult> { const user = await requireUser(); const limit = getMemoryMaxTotal(); if (await prisma.memory.count({ where: { userId: user.id } }) >= limit) return failure(`已达到 ${limit} 条记忆上限，请先删除不再需要的内容。`); const parsed = memoryInputSchema.safeParse(input); if (!parsed.success) return failure("请检查记忆表单。", parsed.error.flatten().fieldErrors as Record<string, string[]>); const data = parsed.data; if (containsHighConfidenceCredential(data.content)) return failure("请勿将密码、API Key 或访问令牌保存为长期记忆。"); const access = await validateMemoryRelations(user.id, data); if (access) return failure(access); if (await duplicateExists(user.id, data.content, data.scope, data.personaId)) return failure("相同的记忆已经存在。"); try { const memory = await prisma.memory.create({ data: { ...memoryData(data), userId: user.id }, select: { id: true } }); revalidatePath("/memories"); return { success: true, id: memory.id, message: data.origin === "CHAT_MESSAGE" ? "已保存为长期记忆" : "记忆已创建。" }; } catch { return failure("记忆保存失败，请稍后重试。"); } }
export async function updateMemoryAction(id: string, input: MemoryInput): Promise<MemoryActionResult> { const user = await requireUser(); if (!memoryIdSchema.safeParse(id).success) return failure("记忆不存在或无权访问。"); const parsed = memoryInputSchema.safeParse({ ...input, origin: "MANUAL", sourceConversationId: undefined, sourceMessageId: undefined }); if (!parsed.success) return failure("请检查记忆表单。", parsed.error.flatten().fieldErrors as Record<string, string[]>); if (containsHighConfidenceCredential(parsed.data.content)) return failure("请勿将密码、API Key 或访问令牌保存为长期记忆。"); const access = await validateMemoryRelations(user.id, parsed.data); if (access) return failure(access); if (await duplicateExists(user.id, parsed.data.content, parsed.data.scope, parsed.data.personaId, id)) return failure("相同的记忆已经存在。"); const result = await prisma.memory.updateMany({ where: { id, userId: user.id }, data: { content: parsed.data.content, category: parsed.data.category, scope: parsed.data.scope, personaId: parsed.data.scope === "PERSONA" ? parsed.data.personaId : null, importance: parsed.data.importance, enabled: parsed.data.enabled } }); if (!result.count) return failure("记忆不存在或无权访问。"); revalidatePath("/memories"); return { success: true, id, message: "记忆已更新。" }; }
export async function setMemoryEnabledAction(id: string, enabled: boolean): Promise<MemoryActionResult> { const user = await requireUser(); if (!memoryIdSchema.safeParse(id).success) return failure("记忆不存在或无权访问。"); const result = await prisma.memory.updateMany({ where: { id, userId: user.id }, data: { enabled } }); if (!result.count) return failure("记忆不存在或无权访问。"); revalidatePath("/memories"); return { success: true, id, message: enabled ? "记忆已启用。" : "记忆已停用。" }; }
export async function setMemoryPinnedAction(id: string, pinned: boolean): Promise<MemoryActionResult> { const user = await requireUser(); if (!memoryIdSchema.safeParse(id).success) return failure("记忆不存在或无权访问。"); const result = await prisma.memory.updateMany({ where: { id, userId: user.id }, data: { pinned } }); if (!result.count) return failure("记忆不存在或无权访问。"); revalidatePath("/memories"); return { success: true, id, message: pinned ? "记忆已置顶。" : "已取消置顶。" }; }
export async function deleteMemoryAction(id: string): Promise<MemoryActionResult> { const user = await requireUser(); if (!memoryIdSchema.safeParse(id).success) return failure("记忆不存在或无权访问。"); const result = await prisma.memory.deleteMany({ where: { id, userId: user.id } }); if (!result.count) return failure("记忆不存在或无权访问。"); revalidatePath("/memories"); return { success: true, message: "记忆已删除。" }; }
export async function setMemoryMasterEnabledAction(enabled: boolean): Promise<MemoryActionResult> { const user = await requireUser(); await prisma.profile.update({ where: { id: user.id }, data: { memoryEnabled: enabled } }); revalidatePath("/memories"); return { success: true, message: enabled ? "长期记忆已开启。" : "长期记忆已关闭，数据仍会保留。" }; }
